spring.application.name=BootDataJPAProj01

#Spring DatSource Details
spring.datasource.driver-class-name = oracle.jdbc.OracleDriver
spring.datasource.url = jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username = shankar
spring.datasource.password = Shankar1234

#Spring data JPA Details
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#Bellow line to see query in console window
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
spring.jpa.hibernate.ddl-auto=update
